from fastapi import APIRouter, HTTPException, Body
from models.schemas import ReportFormatterRequest, ReportFormatterResponse, TotalCalculationResponse
from utils.logger import logger

router = APIRouter()

@router.post("/generate-report", response_model=ReportFormatterResponse)
async def generate_report(request: ReportFormatterRequest = Body(...)):
    try:
        logger.info(f"Generating report for Sheet {request.expense_sheet_id}")

        # --- AUTO-CALCULATE IF MISSING ---
        if not request.total_validation:
            logger.warning("Agent 4 input missing 'total_validation'. Calculating internally.")
            calc_total = sum(i.verified_amount or 0.0 for i in request.single_ocr_validations)
            rept_total = sum(i.employee_reported_amount or 0.0 for i in request.single_ocr_validations)
            
            request.total_validation = TotalCalculationResponse(
                calculated_total=round(calc_total, 2),
                employee_reported_total=round(rept_total, 2),
                matched=abs(calc_total - rept_total) < 0.05,
                discrepancy_amount=round(rept_total - calc_total, 2),
                currency="CHF"
            )
        # ---------------------------------

        totals = request.total_validation
        match_icon = "✅" if totals.matched else "⚠️"
        
        # Build Policy Status String
        policy_status = "✅ <b>Policy Check:</b> All expenses compliant."
        if request.policy_validations:
            violations = [v for v in request.policy_validations if not v.compliant]
            if violations:
                policy_status = f"❌ <b>Policy Check:</b> Found {len(violations)} violations."

        html_content = f"""
        <div style="font-family: Arial, sans-serif; padding: 15px; border: 1px solid #ccc; border-radius: 5px;">
            <h2 style="color: #2c3e50;">🧾 AI Expense Verification Report</h2>
            <p><b>Sheet:</b> {request.expense_sheet_name} (ID: {request.expense_sheet_id})<br>
            <b>Employee:</b> {request.employee_name}</p>
            <hr>
            <h3>📊 Summary</h3>
            <table style="width: 100%; border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;"><b>Claimed Total:</b></td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{totals.currency} {totals.employee_reported_total:.2f}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;"><b>Verified Total:</b></td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{totals.currency} {totals.calculated_total:.2f}</td>
                </tr>
                <tr>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;"><b>Status:</b></td>
                    <td style="padding: 8px; border-bottom: 1px solid #eee;">{match_icon} {"MATCHED" if totals.matched else "DISCREPANCY"}</td>
                </tr>
            </table>
            <p>{policy_status}</p>
            <hr>
            <p style="font-size: 0.9em; color: #7f8c8d;"><i>Generated by Agentic Genie AI • {len(request.single_ocr_validations)} Invoices Processed</i></p>
        </div>
        """

        plain_text = f"Expense Report: {request.expense_sheet_name}. Status: {'MATCHED' if totals.matched else 'DISCREPANCY'}"

        return ReportFormatterResponse(formatted_comment=plain_text, html_comment=html_content)

    except Exception as e:
        logger.error(f"Report generation failed: {str(e)}")
        # Safe fallback to prevent crash
        return ReportFormatterResponse(formatted_comment="Error", html_comment=f"Error: {str(e)}")